server:
  port: 8000
spring:
  application:
    name: api-gateway # 应用名称

# 自定义配置
name: config-api-gateway-dev

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://eureka-server/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
