server:
  port: 8012
spring:
  application:
    name: auth-center # 应用名称
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    user: root
    password: 123123
    virtual-host: /

# 自定义配置
name: config-auth-center-dev

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://127.0.0.1:1001/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id

management:
  endpoints:
    web:
      base-path: /    # 访问端点根路径，默认为 /actuator
      exposure:
        include: bus-refresh  # 需要开启的端点
        #exclude:             # 不需要开启的端点