server:
  port: 8000
spring:
  application:
    name: service-gateway

# 自定义配置
name: config-service-gateway-dev

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://127.0.0.1:1001/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
