server:
  port: 8011
spring:
  application:
    name: user-center # 应用名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PRC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
# 自定义配置
name: config-user-center-dev

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://127.0.0.1:1001/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    # ip-address: ${IP_ADDRESS:127.0.0.1}
    # instance-id: ${spring.application.name}:${server.port} #指定实例id
